### ISSUE TITLE
Update examples of some operators based on the changes for v6

### ISSUE THREAD

**Issue by binDongKim** [btroncone/learn-rxjs#111]
Firstly, I must say this GitBook is really helpful. Great work!

And I think it would be better to update some examples based on the changes for v6 such as import path and deleting result selectors.

I'd love to contribute this but wondering if it's okay to send PR after changing some piece, not the whole operators. 

Thank you!

**Comment by btroncone** [comment]
Thanks for the comment! I'm actually wprlong on updating all examples to v6 right now, should be done with the PR by this weekend. :)

Would love to have your contributions as well, send anything you would like. It does not have to be a whole operator. I look forward to it!

**Comment by binDongKim** [comment]
Sounds wonderful! I look forward to it :D
