### ISSUE TITLE
pluck example #2 links

### ISSUE THREAD

**Issue by aljacinto** [btroncone/learn-rxjs#112]
Hi,

For pluck example#2, the jsbin and jsfiddle examples are going to link with code from example#1

example#1 jsbin link:  http://jsbin.com/zokaxiwahe/1/edit?js,console
example#2 jsbin link:  http://jsbin.com/joqesidugu/1/edit?js,console

example#1 jsfiddle link:  https://jsfiddle.net/btroncone/58v9xq0f/
example#1 jsfiddle link:  https://jsfiddle.net/btroncone/n592m597/

example#2 stackblitz, it is going to the right link but there's error

Would love to fix it but don't know where to start :)

Thanks,
Alex

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
