### ISSUE TITLE
Request: Recepie for shared resource updates

### ISSUE THREAD

**Issue by BasHamer** [btroncone/learn-rxjs#113]
Thank you for the examples, they really help. The only thing that really left me puzzled was how to create a source for the events that don't leak memory. The examples that rely on the timer are great for explaining what should happen after the event, it would rock to have one that delves into how to build the event generation.

Below is the example that I'm trying to find.

Service 1 has a resource that has multiple subscribers.
Subsciber A subscribes to resource
Service 1 has the resource set to initial value (A)
Subscriber B subscribes to resource
Service 1 updates the resource (B)

expected output
subsciber A (AB)
subscriber B (AB)

The service 1 interface would have the following api
The resource
A method to add a new updated resource.

**Comment by btroncone** [comment]
Hello, sorry for the delay. If you are looking to share a stream among multiple subscribers you can checkout `share`, or `shareReplay` (if you want late subscribers to receive latest values). If you want to handle this manually without operators, this is similar to subscribing a `Subject` or `ReplaySubject` to a stream, then subscribing to that `Subject`. 

Please let me know if this helps, if not feel free to share a StackBlitz with your provided use-case and I can dive into it further. Thanks for reading!

**Comment by evdama** [comment]
speaking of subjects... Is there a chapter on subjects or would that be something that's still to be done?

**Comment by adamlubek** [comment]
I can add a documentation/examples of using subjects unless @btroncone is already putting one together?

**Comment by btroncone** [comment]
@adamlubek That would be great, thanks! We can iterate on this one together. 👍👍

**Comment by adamlubek** [comment]
sounds good! :)

**Comment by adamlubek** [comment]
Subjects section is now added, maybe this issue could be closed now?

**Comment by btroncone** [comment]
Closing 👍👍
