### ISSUE TITLE
partition example on stackblitz shows typing error

### ISSUE THREAD

**Issue by mattiLeBlanc** [btroncone/learn-rxjs#115]
When looking at the example I am getting a typing error:

`(Argument of type 'UnaryFunction<Observable<number>, [Observable<number>, Observable<number>]>' is not assignable to parameter of type 'OperatorFunction<any, any>'.)`

I got the same message when I tried to use `partition` in NGRX Effects.

**Comment by iblocks-Xander** [comment]
Related to: https://github.com/ReactiveX/rxjs/issues/2995
With the update to RxJs 6, `pipe` takes an `OperatorFunction`. 

Conceptually, an operator function takes one Observable in, and produces one Observable out. This is incompatible with how partition works, as it takes one Observable in and produces two.

I guess partition documentation should be removed from the repo.

**Comment by mattiLeBlanc** [comment]
@iblocks-Xander I am not sure if the RXJS team is going to keep partition. You can also use GroupBy and FlatMap.
This article explains it nicely: https://www.g9labs.com/2016/02/17/partitioning-rxjs-streams-adventures-in-nested-observables-with-groupby-and-flatmap/

Maybe add an example of that?
