### ISSUE TITLE
The example of retryWhen is not working as expected

### ISSUE THREAD

**Issue by kimamula** [btroncone/learn-rxjs#130]
The second example of `retryWhen` does not actually retry `this._appService.getData(500)`.
I have confirmed this by inserting `console.log('getData', status);` into the getData method in [the StackBlitz example](https://stackblitz.com/edit/angular-cwnknr?file=app%2Frxjs-utils.ts)

https://www.learnrxjs.io/operators/error_handling/retrywhen.html

**Comment by kimamula** [comment]
The following code works.

```ts
of(true, async).pipe(
  flatMap(() => this._appService.getData(500)),
  retryWhen(genericRetryStrategy()),
  catchError(error => of(error))
).subscribe(console.log);
```

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
