### ISSUE TITLE
"Official docs" links point to obsolete repo

### ISSUE THREAD

**Issue by lemoinem** [btroncone/learn-rxjs#158]
The current official RxJS repo is https://github.com/reactivex/rxjs and has been for quite a while. But the "Official docs" links still point to https://github.com/Reactive-Extensions/RxJS

Example: https://www.learnrxjs.io/operators/utility/timeout.html

**Comment by btroncone** [comment]
Thanks! I will get these updated soon. 👍

**Comment by btroncone** [comment]
This has been fixed :)
