### ISSUE TITLE
Adding Documentation for `ajax` operator

### ISSUE THREAD

**Issue by paschalidi** [btroncone/learn-rxjs#175]
Love what you are doing here 🥇 Documentation really helped me when I started with Rxjs and still does 👍 

I have the feeling, and please correct me if I am wrong, that `ajax` operator is missing. 
Can be found [here](https://rxjs-dev.firebaseapp.com/api/ajax/ajax).

I am happy to help you add it. Please let me know if you need any help or if there is a reason that this is not added that I didnt know.

**Comment by btroncone** [comment]
Thanks! Yep that was just overlooked but I agree, it’s very useful and definitely should be added. If you don’t mind submitting a PR that would be amazing!

**Comment by paschalidi** [comment]
@btroncone if you dont mind assigning this to me that would be great. Then I can take care of it :)

**Comment by btroncone** [comment]
Done :)

**Comment by paschalidi** [comment]
@btroncone in which category of would you have `ajax` under?
the import is like 
```
import { ajax } from 'rxjs/ajax';
``` 
Not sure where we want this to live.

**Comment by btroncone** [comment]
I would put it under ‘creation’, thanks!

**Comment by paschalidi** [comment]
thanks for the quick response!

**Comment by paschalidi** [comment]
@btroncone can you please close this one if you feel that is complete?
