### ISSUE TITLE
need example to make more clear bufferWithTimeOrCount

### ISSUE THREAD

**Issue by salisbury-espinosa** [btroncone/learn-rxjs#177]
spec of bufferWithTimeOrCount: http://reactivex.io/documentation/operators/buffer.html
implementation: https://github.com/ReactiveX/rxjs/pull/1556
need an example in order to make more clear the behavior in https://www.learnrxjs.io/operators/transformation/buffertime.html
+
need change signature for `bufferTime` from
```js 
bufferTime(bufferTimeSpan: number, bufferCreationInterval: number, scheduler: Scheduler): Observable
```
in accordance with
https://github.com/ReactiveX/rxjs/blob/441d52208df8b9247b01f8ca3993e3a7b0870b10/src/internal/operators/bufferTime.ts#L12

**Comment by btroncone** [comment]
Thanks for the feedback and my apologies for the delay. I'll look into updating this in the next few days 👍

**Comment by jankoritak** [comment]
Bumping this. Can submit a PR, if interested.

**Comment by btroncone** [comment]
@jankoritak That would be great! 👍

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
