### ISSUE TITLE
catch-spec: error variable

### ISSUE THREAD

**Issue by julioxavierr** [btroncone/learn-rxjs#202]
Usually we can do something like this inside our Observables, throw an error with a message. As in [RxJS docs](https://rxjs-dev.firebaseapp.com/guide/observable).

```
observer.error('Not authorized to record audio');
```

Is it possible to specify here, when testing, what is the message of the error too?
Maybe attributing a variable to it, as we do with usual values emitted.
https://github.com/btroncone/learn-rxjs/blob/5dad48774bd55984d7ebadec47ce71901c86fde5/operators/specs/error_handling/catch-spec.ts#L11

If so, it would be great to have an example for this also.

**Comment by julioxavierr** [comment]
Just discovered that we can use the 3rd parameter for this

```
    const source = cold('#', {}, 'Error description')
```

**Comment by btroncone** [comment]
Thanks! Sorry there is not a better example for that, the marble tests are a bit out of date at this point. Hope to have a better overall section covering marble testing in the coming months. 👍
