### ISSUE TITLE
(suggestion) usage pluck for arrays

### ISSUE THREAD

**Issue by Pucek9** [btroncone/learn-rxjs#205]
pluck can be used after combineLatest/withLatestFrom as well

`map(([unusedValue, usedValue]) => usedValue)`
can be replaced by
`pluck(1)`

It's not documented. Can be?

**Comment by btroncone** [comment]
This is an interesting use case I had not thought of, let me think about it a little more. It definitely works, I'm just not sure if it should be encourage or not :)

Thanks for bringing this up!

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
