### ISSUE TITLE
I cannot find refCount nor publishReplay anymore

### ISSUE THREAD

**Issue by carlosdubus** [btroncone/learn-rxjs#215]
Hello. I love the site, I use it often, thanks for your work! I noticed refCount and publishReplay are no longer on the site. Is this intentional?
Thanks!

**Comment by btroncone** [comment]
Nope, thanks for the issue! I do need to add `refCount` as it's the base for many other operators. I think I missed it because I generally use `share` or `shareReplay` instead.

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
