### ISSUE TITLE
tetris game impure function

### ISSUE THREAD

**Issue by mohaalak** [btroncone/learn-rxjs#232]
I love how you wanted to code tetris game with rxjs but I think it could be more elegant  
`handleKeyPress` and `rotate` and `collide`  and `score` they all mutate state but it was better that it return a new state

**Comment by btroncone** [comment]
Thanks for the feedback! Tagging @adamlubek if you want to discuss the solution further. 👍

**Comment by adamlubek** [comment]
@mohaalak you're right, it would be much nicer for these function to be pure, thanks for pointing this out! I'll try to correct this soon or alternatively feel free to submit PR and I'll update stackblitz code :)

**Comment by btroncone** [comment]
@adamlubek This has been resolved?

**Comment by adamlubek** [comment]
yes :) this PR resolved it: https://github.com/btroncone/learn-rxjs/pull/237

**Comment by btroncone** [comment]
Thanks, closing! 👍
