### ISSUE TITLE
https://www.learnrxjs.io offline

### ISSUE THREAD

**Issue by pietermarsman** [btroncone/learn-rxjs#249]
Since yesterday I can't reach https://www.learnrxjs.io anymore.

I really regret this because I love the overview and examples.

**Comment by btroncone** [comment]
Just double checked on my end and it seems to be working fine, are you receiving some sort of error message? @adamlubek, are you able to reach the site?

**Comment by adamlubek** [comment]
working on my end too

**Comment by pietermarsman** [comment]
Hhm, strange! Yesterday, I got the a message from safari that it wasn't able to reach https://www.learnrxjs.io, no http error message. Both on my phone and laptop. Today, it is working for me again.
