### ISSUE TITLE
Rx.Observable.merge seems to return an array not a new observable

### ISSUE THREAD

**Issue by ORESoftware** [btroncone/learn-rxjs#26]
Not sure if this is a doc bug or library bug but

Rx.Observable.merge seems to return an array not a new observable

but the docs say:

```
signature: merge(input: Observable): Observable

Turn multiple observables into a single observable.
Rx.Observable.timer(1)
```

here is my proof:

![screenshot from 2017-01-09 20-32-26](https://cloud.githubusercontent.com/assets/11139560/21793977/fe3f3938-d6aa-11e6-8099-a46807339ed3.png)

lastly I want to say thank you for these docs, hopefully I am right about this bug, and in that case very willing to tolerate a little bit of wonkiness for a bit, thanks

**Comment by btroncone** [comment]
Hello, 

It looks like you are calling it wrong. `merge` takes a variable number of observables, not an array. Try calling it like this:

```ts
const example = Rx.Observable.of(
 Rx.Observable.timer(1),
 Rx.Observable.timer(1),
 Rx.Observable.timer(1)
)
```

This should give you the correct behavior. 👍

**Comment by ORESoftware** [comment]
thanks! :) hate to beat a horse, but why not allow for an array as well? I am sure I am not the only one to make such a mistake or to make the same request!

**Comment by ORESoftware** [comment]
oh duh, if you allow for an array, it will return an array. Ughhh I think it's bad the way it is.

`Rx.Observable.merge` or` Rx.Observable.of` should return the same type, no matter what the input.

Right now `Rx.Observable.merge` will return an array, if an array is passed to it, and an Observable otherwise, that's pretty craytown TBH

**Comment by btroncone** [comment]
I agree the behavior seems a little strange. I cannot speak to the intentions though, for that you will need to open up a ticket on [official RxJS repo](https://github.com/ReactiveX/rxjs). Feel free to post a link here if you do. 👍

**Comment by ORESoftware** [comment]
yeah thanks; I think in general with statically typed languages you can have overloaded functions/methods that return different types based off the input, but with JS and no real overloaded methods/functions, it sure would make things easier if methods/functions always returned the same type

**Comment by ORESoftware** [comment]
I did submit an issue, we will see what they say

https://github.com/ReactiveX/rxjs/issues/2274

thanks!
