### ISSUE TITLE
distinctUntilKeyChanged link is 404

### ISSUE THREAD

**Issue by nfedyashev** [btroncone/learn-rxjs#267]
distinctUntilKeyChanged link from this page: https://www.learnrxjs.io/learn-rxjs/operators seems to be broken.

https://github.com/btroncone/learn-rxjs/tree/a395b6202c4b985e760736a3dc96103b5495d427/operators/distinctuntilkeychanged.md

**Comment by nfedyashev** [comment]
same with dematerialize

**Comment by btroncone** [comment]
Thanks! Updated 👍
