### ISSUE TITLE
Is there any plans to update the documentation?

### ISSUE THREAD

**Issue by coldrain96** [btroncone/learn-rxjs#311]
Hi there, 

Thank you for this awesome version of RxJS documentation, it's really good. I spent a lot of time studying the examples. 

I wonder do you have any plans to update the documentation, because it's becoming outdated. Most of the pages are already outdated for several years. The v8.0.0 on its way and coming fastly. I'd glad to take participation in migration.

**Comment by btroncone** [comment]
Hello, thanks for the comment and kind words. I do plan to keep it updated. I think the examples are still relevant to the current version of RxJS. If you can point to specifics that need to be updated then in can work on that, always thankful for PRs as well. Thanks!
