### ISSUE TITLE
Incorrect example combineAll 

### ISSUE THREAD

**Issue by Cogitaria** [btroncone/learn-rxjs#36]
```
//emit every 1s, take 2
const source = Rx.Observable.interval(1000).take(2);
//map first value to 500ms interval **and second to 1s,** take two values
const example = source.map(val => Rx.Observable.interval(val + 500).take(2));
```

The first source value is mapped to interval of 0 + 500 (half second) and the second to 1 + 500 (that's not one second).  Also you could choose 25 instead of 500 in the original example:  the output is the same. You could choose 2000 instead of 500: the output is the same. The example should focus on combineAll, clear of misleading comments.

**Comment by btroncone** [comment]
It looks like I had updated this on jsFiddle a while back but forgot to update markdown example. I apologize for any confusion.
