### ISSUE TITLE
Simple easing in smart counter example

### ISSUE THREAD

**Issue by seveves** [btroncone/learn-rxjs#38]
I'm trying to understand how I can apply some simple easing function to the [smart counter example](https://github.com/btroncone/learn-rxjs/blob/master/recipes/smartcounter.md) but all I could achieve is that only the first execution was delayed.

For example I did something like that:
```
.delayWhen((i) => {
  return Rx.Observable.interval(i + 1000);
 })
```

**Comment by LarryBattle** [comment]
`Rx.Observable.interval()` takes in milliseconds. So to add a second delay you need to multiply by 1000, not add. 

```
.delayWhen((i) => {
  return Rx.Observable.interval(i * 1000);
 })
```

Demo: https://jsfiddle.net/au4sqvxu/9/

**Comment by seveves** [comment]
Thanks for the fiddle and yes you are right with the delay but I was asking for a way to add 'easing'. For example I want to accelerate the counter with each step.

**Comment by deanius** [comment]
@seveves I think you want a concatenation of a bunch of observables, each one shorter than the next.

range(1000, 500).concatMap(msec => Observable.delay(msec))

```
|--4--3--2--1-->
   \  \  \  \
    \  \  \  v
     \  \  v
      \  v
       v

through concatMap becomes:

|---->|--->|-->|->
```

**Comment by btroncone** [comment]
Closing - cleaning up old issues.
