### ISSUE TITLE
GroupBy example

### ISSUE THREAD

**Issue by sant123** [btroncone/learn-rxjs#56]
The example of [groupBy](https://github.com/btroncone/learn-rxjs/blob/master/operators/transformation/groupby.md) uses `.flatMap(group => group.reduce((acc, curr) => [...acc, curr], []))`. Is it not better to use `.flatMap(group => group.toArray())`? Or does it have a performance impact? This is the full code:

```js
const Rx = require("rxjs");

const people = [{ name: 'Sue', age: 25 }, { name: 'Joe', age: 30 }, { name: 'Frank', age: 25 }, { name: 'Sarah', age: 35 }];
//emit each person
const source = Rx.Observable.from(people);
//group by age
const example = source
    .groupBy(person => person.age)
    //return as array of each group
    .flatMap(group => group.toArray())
    // .flatMap(group => group.reduce((acc, curr) => [...acc, curr], []))
    /*
      output:
      [{age: 25, name: "Sue"},{age: 25, name: "Frank"}]
      [{age: 30, name: "Joe"}]
      [{age: 35, name: "Sarah"}]
    */
const subscribe = example.subscribe(console.log);
```

Thank you!

**Comment by btroncone** [comment]
@sant123 Good find, I think either will work perfectly fine but your version is more clear. I will update the example accordingly, thanks! 👍

**Comment by sant123** [comment]
Great! :smiley:

Thanks to you!

**Comment by btroncone** [comment]
Updated 👍
