### ISSUE TITLE
Website https://www.learnrxjs.io down

### ISSUE THREAD

**Issue by MartinNuc** [btroncone/learn-rxjs#67]
Are there some issues with website https://www.learnrxjs.io

It seems to be down.

**Comment by lazarljubenovic** [comment]
Appears to be working here fine.

**Comment by btroncone** [comment]
I'm not seeing any issues on my end, is anyone's else having problems?

**Comment by minajevs** [comment]
Works fine for me

**Comment by MartinNuc** [comment]
Works for me too. I will try from work next year. Maybe some firewall issue or site started to work.

**Comment by theRealAbdurrahman** [comment]
I think it is down again..
It gives me 
> www.learnrxjs.io’s server IP address could not be found.
> ERR_NAME_NOT_RESOLVED

**Comment by btroncone** [comment]
Hmm, it’s workinf for me right now but looking into it further. Thanks!

**Comment by MartinNuc** [comment]
I asked our specialist and he told me that gitbook.io has incorrect DNS. In my case I had to disconnect our VPN.
