### ISSUE TITLE
Switchmap: Example 4: Countdown timer with switchMap could be clearer

### ISSUE THREAD

**Issue by khaing211** [btroncone/learn-rxjs#90]
Hi,

It takes a while to understand "Example 4: Countdown timer with switchMap" on 
https://www.learnrxjs.io/operators/transformation/switchmap.html

Mostly, my confusion is due to ```startsWith(interval$)```.

Original code:
```
const timer$ = merge(pause$, resume$)
  .pipe(
    startWith(interval$),
    switchMap(val => (val ? interval$ : empty())),
    scan((acc, curr) => (curr ? curr + acc : acc), countdownSeconds),
    takeWhile(v => v >= 0)
  )
  .subscribe(setHTML('remaining'));
```

I think it is better to have ```startsWith(true)``` there because we want to start the timer right away. And, I am not sure what is the effects of having ```startsWith(interval$)```, because testing on jsfiddle shows that the code has no effects.

Newly purposed code:
```
const timer$ = merge(pause$, resume$)
  .pipe(
    startWith(true),
    switchMap(val => (val ? interval$ : empty())),
    scan((acc, curr) => (curr ? curr + acc : acc), countdownSeconds),
    takeWhile(v => v >= 0)
  )
  .subscribe(setHTML('remaining'));
```

**Comment by btroncone** [comment]
Thanks for the issue! Very good point, `interval$` in `startsWith` serves no purpose. I will update today. 👍

**Comment by btroncone** [comment]
Closing as updated.
